### ISSUE TITLE
Изображение с камеры в диалоге авторизации.

### ISSUE THREAD

**Issue by alexis031182** [ruFog/facetracker#3]
Предлагаю вывести изображение с камеры непосредственно в диалоговом окне авторизации. Во-первых, пользователь сразу увидит, работает ли устройство или нет, во-вторых, от него не потребуется щёлкать по соответствующей кнопке (в данном случае это становится принципиальным, поскольку состояние камеры является основополагающим для работы всего приложения), а, в-третьих, не будет кучи всплывающих окон, что зачастую только путает.

**Comment by ostretsov** [comment]
Согласен!

**Comment by alexis031182** [comment]
Я добавлю коммит и тогда закроем, я переассигновал этот таск на себя.
