### ISSUE TITLE
Баг при перезапуске видеозахвата

### ISSUE THREAD

**Issue by alexis031182** [ruFog/facetracker#4]
Неожиданно для меня таковой обнаружился. Не очень ясно, чья недоделка, то ли убунты, то ли opencv, а то ли обоих разом, но факт. Возникает сегфолт при закрытии и попытке повторного открытия устройства. Решение нашёл [здесь](http://stackoverflow.com/questions/5033253/grabbing-images-from-a-webcam-to-be-used-with-opencv), проверил - у меня работает, однако уж очень смахивает на костыль. Не знаю пока, как быть.

Суть обозначенного решения, добавить предзагрузку **v4l1compat.so** из пакета **libv4l** следующей командой:

```
export LD_PRELOAD=/usr/lib/i386-linux-gnu/libv4l/v4l1compat.so
```

**Comment by ostretsov** [comment]
Это приемлемое решение

**Comment by alexis031182** [comment]
При использовании данного решения происходит утечка памяти из-за невозможности высвобождения "моста" (memory mapping). Проблему устраняет реализация видеозахвата посредством ffmpeg.

**Comment by alexis031182** [comment]
[Обсуждение и решение](http://ru.stackoverflow.com/questions/427812/%D0%9F%D0%B5%D1%80%D0%B5%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%D0%B7%D0%B0%D1%85%D0%B2%D0%B0%D1%82%D0%B0)
