### ISSUE TITLE
Предложение об ином расположении параметров приложения.

### ISSUE THREAD

**Issue by alexis031182** [ruFog/facetracker#5]
Предлагаю вынести параметры из таблицы "settings" БД в ini-файл. И редактировать проще, и считывать/записывать данные из/в таблицу также значительно легче. Просто из-за того, что таблицы обычно создаются с идентификатором строки, а так, для того, чтобы прочитать значение параметра или записать новое придётся делать "селект" по всей таблице и сравнивать наименования параметров, что, мягко говоря, не очень хорошо.

**Comment by ostretsov** [comment]
Ок!

**Comment by ostretsov** [comment]
В этом случае не нужно в ini-файл писать сессионные данные и временную метку, полученную с сервера. Также желательно создавать при каждом запуске лог файл, в который валится отладочная информация при каждом запросе: тело запроса, тело ответа, заголовки ответа с сервера. При каждом запуске этот файл пересоздается.

**Comment by alexis031182** [comment]
Логи пишутся в БД. Для этого там уже создана таблица "messages". Id строки, всё, как положено, там есть. Единственное, действительно ли нужно записывать заголовки http-запросов/ответов? С телом ответов и запросов - понятно, а заголовки зачем?

**Comment by ostretsov** [comment]
Это удобно в том числе мне, чтобы проверить что сервер отвечает корректно (статус код, дата, content-type и т.д.). Как минимум один заголовок будет использоваться в этом приложении: Server-Time.
